---
- hosts: identidock
  become: true
  tasks:
    - name: Ensure redis container is running.
      docker_container:
        name: redis
        image: redis:6.0
        pull: true
        restart_policy: always
    - name: Ensure dnmonster container is running.
      docker_container:
        name: dnmonster
        image: amouat/dnmonster:1.0
        pull: true
        restart_policy: always
    - name: Ensure identidock container is running.
      docker_container:
        name: identidock
        image: amouat/identidock:1.0
        pull: true
        links:
          - "dnmonster:dnmonster"
          - "redis:redis"
        env:
          ENV: PROD
        restart_policy: always
    - name: Ensure proxy container is running.
      docker_container:
        name: proxy
        image: amouat/proxy:1.0
        pull: true
        links:
          - "identidock:identidock"
        ports:
          - "80:80"
        env:
          NGINX_HOST: www.identidock.com
          NGINX_PROXY: http://identidock:9090
        restart_policy: always
