version: "2"
services:
  proxy:
    image: amouat/proxy:1.0
    links:
      - identidock
    ports:
     - "80:80"
    environment:
      - NGINX_HOST=192.168.0.100
      - NGINX_PROXY=http://identidock:9090

  identidock:
    image: amouat/identidock:1.0
    links:
     - dnmonster
     - redis
    environment:
      ENV: PROD

  dnmonster:
    image: amouat/dnmonster

  redis:
    image: redis

  logspout:
    image: amouat/logspout-logstash
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "8000:80"
    links:
      - logstash
    environment:
      ROUTE_URIS: logstash://logstash:5000

  logstash:
    image: logstash:1.5
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
    environment:
      LOGSPOUT: ignore
    command: -f /usr/share/logstash/config/logstash.conf
