version: "3"
services:
  proxy:
    image: amouat/proxy:1.0
    links:
      - identidock
    ports:
     - "80:80"
    environment:
      - NGINX_HOST=192.168.0.100
      - NGINX_PROXY=http://identidock:9090

  identidock:
    image: amouat/identidock:1.0
    links:
     - dnmonster
     - redis
    environment:
      ENV: PROD

  dnmonster:
    image: amouat/dnmonster

  redis:
    image: redis

  logspout:
    image: amouat/logspout-logstash
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - "8000:80"
    links:
      - logstash
    environment:
      ROUTE_URIS: logstash://logstash:5000

  logstash:
    image: logstash:7.8.0
    container_name: logstash
    hostname: logstash
    environment:
      LOGSPOUT: ignore
    ports:
      - 9600:9600
      - 8089:8089
    volumes:
      - ./logstash.conf:/usr/share/logstash/config/logstash.conf
    command: -f /usr/share/logstash/config/logstash.conf
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      discovery.type: single-node  
      LOGSPOUT: ignore
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data 
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: kibana:7.8.0
    container_name: kibana
    hostname: kibana
    environment:
      LOGSPOUT: ignore
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
    driver: local